title: <p align="center"> Ravi Shankar Shukla </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="Ravi_Resume - Copy.docx">Resume</a> |
  <a href="https://www.linkedin.com/in/ravi4mindia/">LinkedIn</a> |
  <a href="https://github.com/ravi-maker">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  Worked with Sabre and Boeing Research Analytics team.
  
  <br>
  </p>



theme: jekyll-theme-minimal